steps:
# pull the latest from repo branch: development
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/peterchang04/projectm.git']
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch']
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'development']
# install package.json
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
# yarn globals
- name: 'gcr.io/cloud-builders/yarn'
  args: ['global', 'add', '@vue/cli']
# build Dockerfile_cloudbuild locally -- substitutions stored at cloud build trigger
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
    '-t', 'gcr.io/projectmvue/development:$REVISION_ID',
    '-f', 'Dockerfile_cloudbuild',
    '--build-arg', 'env=${_ENV}',
    '--build-arg', 'apiroot=${_API_ROOT}',
    '--build-arg', 'revision_id=$REVISION_ID',
    '.'
  ]
# push ready-to-deploy image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/projectmvue/development:$REVISION_ID']
# create a new instance template, to update instance groups to.
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta', 'compute', 'instance-templates',
    'create-with-container', 'projectm-instancetemplate-development-$REVISION_ID',
    '--container-image', 'gcr.io/projectmvue/development:$REVISION_ID',
    '--boot-disk-device-name', 'projectm-instancetemplate-development-bootdisk-$REVISION_ID',
    '--boot-disk-size', '10GB',
    '--boot-disk-type', 'pd-standard',
    '--machine-type', 'f1-micro',
    '--maintenance-policy', 'MIGRATE',
    '--region', 'us-west1',
    '--image-family', 'cos-stable'
  ]
# update cloud instance group with latest image
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta', 'compute', 'instance-groups', 'managed', 'rolling-action',
    'start-update', 'projectm-instancegroup-development',
    '--version', 'template=projectm-instancetemplate-development-$REVISION_ID',
    '--zone', 'us-west1-b'
  ]
# build Dockerfile_local, for local development -- substitutions stored at cloud build trigger
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
    '-t', 'gcr.io/projectmvue/local',
    '-f', 'Dockerfile_local',
    '--build-arg', 'env=${_ENV_LOCAL}',
    '--build-arg', 'apiroot=${_API_ROOT_LOCAL}',
    '--build-arg', 'revision_id=$REVISION_ID',
    '.'
  ]
# push local development image to container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/projectmvue/local']
