steps:
# pull the latest from repo branch: development
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/peterchang04/projectm.git']
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch']
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'development']
# install package.json
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
# yarn globals
- name: 'gcr.io/cloud-builders/yarn'
  args: ['global', 'add', '@vue/cli']
# build docker image locally
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/projectmvue/development', '-f', 'Dockerfile_cloudbuild', '.']
# push ready-to-deploy image to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/projectmvue/development']
# deploy to kubernetes 1st time only, in absence of Kube Engine/Workload
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud app deploy ~/app.yaml
