# read by google cloud build - cloudbuild.yaml
FROM node:8.11-alpine
MAINTAINER peter

# Ports
ENV PORT 80
EXPOSE 80

# Directories
ENV APP_DIR /app
WORKDIR $APP_DIR

# Environment Defaults - see instance template
ARG env=local
ARG apiroot=http://localhost:51337
ARG revision_id=unavailable

# Environment Variables
ENV env=$env
ENV apiroot=$apiroot
ENV revision_id=$revision_id

# Copy package manager files
COPY package*.json ./
COPY yarn.lock ./

# Copy Current dir into image
COPY . $APP_DIR

# Copy Environment Variables to /.env (vue config)
RUN sed -i "s|VUE_APP_ENV=|VUE_APP_ENV=$env |g" $APP_DIR/.env \
 && sed -i "s|VUE_APP_APIROOT=|VUE_APP_APIROOT=$apiroot |g" $APP_DIR/.env \
 && sed -i "s|VUE_APP_REVISION_ID=|VUE_APP_REVISION_ID=$revision_id |g" $APP_DIR/.env

# Get Dependencies
RUN yarn install \
 && yarn global add @vue/cli \
 && yarn build

# Healthcheck
ENV HEALTHCHECK_URI "http://127.0.0.1:${PORT}/"
HEALTHCHECK --interval=20s --timeout=30s --retries=15 CMD curl --fail ${HEALTHCHECK_URI} || exit 1

# Launch express server
CMD yarn serveDist
