# used for local development - built by cloudbuild
FROM node:8.11-alpine
MAINTAINER peter

# Ports
ENV PORT 80
EXPOSE 80

# Directories
ENV APP_DIR /app
WORKDIR $APP_DIR

# Environment Defaults - see build trigger for values passed in
ARG env=
ARG apiroot=
ARG revision_id=

# Environment Variables
ENV env=$env
ENV apiroot=$apiroot
ENV revision_id=$revision_id

# Copy package manager files
COPY package*.json ./
COPY yarn.lock ./

# Get Dependencies
RUN yarn install \
  && yarn global add @vue/cli

# Copy Environment Variables to /.env (vue config)
RUN sed -i "s|VUE_APP_ENV=|VUE_APP_ENV=$env |g" $APP_DIR/.env \
 && sed -i "s|VUE_APP_APIROOT=|VUE_APP_APIROOT=$apiroot |g" $APP_DIR/.env \
 && sed -i "s|VUE_APP_REVISION_ID=|VUE_APP_REVISION_ID=$revision_id |g" $APP_DIR/.env

# Healthcheck
HEALTHCHECK --interval=20s --timeout=12s --start-period=30s --retries=3 CMD node healthcheck.js

# enable hot loading within container
ENV CHOKIDAR_USEPOLLING=true

# Launch
CMD yarn run serve
