# used for local development - built by cloudbuild
FROM node:8.11-alpine
MAINTAINER peter

# Ports
ENV PORT 80
EXPOSE 80

# Directories
ENV APP_DIR /app
WORKDIR $APP_DIR

# Environment Defaults
ARG env_default=local
ARG apiroot_default=http://localhost:51337
ARG revision_id=unavailable

# Environment Variables
ENV env=$env_default
ENV apiroot=$apiroot_default
ENV revision_id=$revision_id

# Copy package manager files
COPY package*.json ./
COPY yarn.lock ./

# Get Dependencies
RUN yarn install \
  && yarn global add @vue/cli

# Healthcheck
HEALTHCHECK --interval=20s --timeout=12s --start-period=30s --retries=3 CMD node healthcheck.js

# enable hot loading within container
ENV CHOKIDAR_USEPOLLING=true

# Launch
CMD yarn run serve
